version: '3.8'

services:
  loadboard-scraper:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 512m
    shm_size: 512m
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M